//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var AccessType = &struct {
	AccessKeys       postgres.StringExpression
	CrossAccountRole postgres.StringExpression
}{
	AccessKeys:       postgres.NewEnumValue("ACCESS KEYS"),
	CrossAccountRole: postgres.NewEnumValue("CROSS ACCOUNT ROLE"),
}
