//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Alerts = newAlertsTable("public", "alerts", "")

type alertsTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	Name              postgres.ColumnString
	Description       postgres.ColumnString
	Configurations    postgres.ColumnString
	ProviderAccountID postgres.ColumnString
	Metadata          postgres.ColumnString
	IsDeleted         postgres.ColumnBool
	CreatedAt         postgres.ColumnTimestampz
	UpdatedAt         postgres.ColumnTimestampz
	DeletedAt         postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type AlertsTable struct {
	alertsTable

	EXCLUDED alertsTable
}

// AS creates new AlertsTable with assigned alias
func (a AlertsTable) AS(alias string) *AlertsTable {
	return newAlertsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AlertsTable with assigned schema name
func (a AlertsTable) FromSchema(schemaName string) *AlertsTable {
	return newAlertsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AlertsTable with assigned table prefix
func (a AlertsTable) WithPrefix(prefix string) *AlertsTable {
	return newAlertsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AlertsTable with assigned table suffix
func (a AlertsTable) WithSuffix(suffix string) *AlertsTable {
	return newAlertsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAlertsTable(schemaName, tableName, alias string) *AlertsTable {
	return &AlertsTable{
		alertsTable: newAlertsTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newAlertsTableImpl("", "excluded", ""),
	}
}

func newAlertsTableImpl(schemaName, tableName, alias string) alertsTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		NameColumn              = postgres.StringColumn("name")
		DescriptionColumn       = postgres.StringColumn("description")
		ConfigurationsColumn    = postgres.StringColumn("configurations")
		ProviderAccountIDColumn = postgres.StringColumn("provider_account_id")
		MetadataColumn          = postgres.StringColumn("metadata")
		IsDeletedColumn         = postgres.BoolColumn("is_deleted")
		CreatedAtColumn         = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampzColumn("updated_at")
		DeletedAtColumn         = postgres.TimestampzColumn("deleted_at")
		allColumns              = postgres.ColumnList{IDColumn, NameColumn, DescriptionColumn, ConfigurationsColumn, ProviderAccountIDColumn, MetadataColumn, IsDeletedColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
		mutableColumns          = postgres.ColumnList{NameColumn, DescriptionColumn, ConfigurationsColumn, ProviderAccountIDColumn, MetadataColumn, IsDeletedColumn, CreatedAtColumn, UpdatedAtColumn, DeletedAtColumn}
	)

	return alertsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		Name:              NameColumn,
		Description:       DescriptionColumn,
		Configurations:    ConfigurationsColumn,
		ProviderAccountID: ProviderAccountIDColumn,
		Metadata:          MetadataColumn,
		IsDeleted:         IsDeletedColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,
		DeletedAt:         DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
