//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var MetricPanels = newMetricPanelsTable("public", "metric_panels", "")

type metricPanelsTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	Name              postgres.ColumnString
	Description       postgres.ColumnString
	Panels            postgres.ColumnString
	ProviderAccountID postgres.ColumnString
	Metadata          postgres.ColumnString
	IsDeleted         postgres.ColumnBool
	CreatedAt         postgres.ColumnTimestampz
	UpdatedAt         postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type MetricPanelsTable struct {
	metricPanelsTable

	EXCLUDED metricPanelsTable
}

// AS creates new MetricPanelsTable with assigned alias
func (a MetricPanelsTable) AS(alias string) *MetricPanelsTable {
	return newMetricPanelsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MetricPanelsTable with assigned schema name
func (a MetricPanelsTable) FromSchema(schemaName string) *MetricPanelsTable {
	return newMetricPanelsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MetricPanelsTable with assigned table prefix
func (a MetricPanelsTable) WithPrefix(prefix string) *MetricPanelsTable {
	return newMetricPanelsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MetricPanelsTable with assigned table suffix
func (a MetricPanelsTable) WithSuffix(suffix string) *MetricPanelsTable {
	return newMetricPanelsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMetricPanelsTable(schemaName, tableName, alias string) *MetricPanelsTable {
	return &MetricPanelsTable{
		metricPanelsTable: newMetricPanelsTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newMetricPanelsTableImpl("", "excluded", ""),
	}
}

func newMetricPanelsTableImpl(schemaName, tableName, alias string) metricPanelsTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		NameColumn              = postgres.StringColumn("name")
		DescriptionColumn       = postgres.StringColumn("description")
		PanelsColumn            = postgres.StringColumn("panels")
		ProviderAccountIDColumn = postgres.StringColumn("provider_account_id")
		MetadataColumn          = postgres.StringColumn("metadata")
		IsDeletedColumn         = postgres.BoolColumn("is_deleted")
		CreatedAtColumn         = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn         = postgres.TimestampzColumn("updated_at")
		allColumns              = postgres.ColumnList{IDColumn, NameColumn, DescriptionColumn, PanelsColumn, ProviderAccountIDColumn, MetadataColumn, IsDeletedColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns          = postgres.ColumnList{NameColumn, DescriptionColumn, PanelsColumn, ProviderAccountIDColumn, MetadataColumn, IsDeletedColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return metricPanelsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		Name:              NameColumn,
		Description:       DescriptionColumn,
		Panels:            PanelsColumn,
		ProviderAccountID: ProviderAccountIDColumn,
		Metadata:          MetadataColumn,
		IsDeleted:         IsDeletedColumn,
		CreatedAt:         CreatedAtColumn,
		UpdatedAt:         UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
