//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type AccessType string

const (
	AccessType_AccessKeys       AccessType = "ACCESS KEYS"
	AccessType_CrossAccountRole AccessType = "CROSS ACCOUNT ROLE"
)

func (e *AccessType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "ACCESS KEYS":
		*e = AccessType_AccessKeys
	case "CROSS ACCOUNT ROLE":
		*e = AccessType_CrossAccountRole
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for AccessType enum")
	}

	return nil
}

func (e AccessType) String() string {
	return string(e)
}
