//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type HealthStatus string

const (
	HealthStatus_Disconnected HealthStatus = "DISCONNECTED"
	HealthStatus_Active       HealthStatus = "ACTIVE"
)

func (e *HealthStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "DISCONNECTED":
		*e = HealthStatus_Disconnected
	case "ACTIVE":
		*e = HealthStatus_Active
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for HealthStatus enum")
	}

	return nil
}

func (e HealthStatus) String() string {
	return string(e)
}
