//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type TimeSeries struct {
	ID                 int32 `sql:"primary_key"`
	TruncatedTimestamp int64 `sql:"primary_key"`
	Series             string
	Type               MetricType
	MetricPanelID      uuid.UUID
	CreatedAt          *time.Time
	UpdatedAt          *time.Time
}
