//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Users struct {
	ID                   uuid.UUID `sql:"primary_key"`
	Username             string
	Email                string
	AvatarURL            *string
	SubscribedSince      *time.Time
	SubscriptionDaysLeft *int32
	LastLoginAt          *time.Time
	Metadata             *string
	IsDeleted            *bool
	CreatedAt            *time.Time
	UpdatedAt            *time.Time
	SubscriptionPlanID   *int32
}
